name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Verificación de Bootstrap
      id: verificacion-de-bootstrap
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Verificación de Bootstrap
        setup-command: ''
        command: grep -i "bootstrap" index.html
        timeout: 1
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VERIFICACION-DE-BOOTSTRAP_RESULTS: "${{steps.verificacion-de-bootstrap.outputs.result}}"
      with:
        runners: verificacion-de-bootstrap
